### ISSUE TITLE
user/nickname Response data differs from API specification

### ISSUE THREAD

**Issue by AstridQuiin** [VirtualPetHospital/backend#21]
- in API document, response is specified as
```
{
    "code": 0,
    "msg": "用户名可用",
    "data": null
}
```
- but its implementation is
```
{
    "code": 0,
    "msg": "操作成功",
    "data": true
}
```

**Comment by QYR22** [comment]
[缺陷问题报告单_user用户-check_nickname](https://r0o7ljwxopa.feishu.cn/sheets/UN3Vsmw51hQCu7t4EpXcsopMnit?sheet=0Ilxux)
