### ISSUE TITLE
users/user_list error content should be refined

### ISSUE THREAD

**Issue by AstridQuiin** [VirtualPetHospital/backend#23]
error code & error msg are not accurate when `page_size` is a double while it should be an integer.
```
{
    "code": -1,
    "msg": "系统异常，请稍后再试",
    "data": null
}
```

**Comment by QYR22** [comment]
[缺陷问题报告单_user用户-user-list](https://r0o7ljwxopa.feishu.cn/sheets/UN3Vsmw51hQCu7t4EpXcsopMnit?sheet=0ncO4G)
