### ISSUE TITLE
users/delete_user error content should be refined

### ISSUE THREAD

**Issue by pikaqiuswd** [VirtualPetHospital/backend#27]
error code & error msg are not accurate when user_id is not valid.
```
{
    "code": -1,
    "msg": "系统异常，请稍后再试",
    "data": null
}
```

**Comment by QYR22** [comment]
[缺陷问题报告单_user用户-delete](https://r0o7ljwxopa.feishu.cn/sheets/UN3Vsmw51hQCu7t4EpXcsopMnit?sheet=QsOOwE)
