### ISSUE TITLE
exams/enroll cannot enroll while student is unenrolled...

### ISSUE THREAD

**Issue by AstridQuiin** [VirtualPetHospital/backend#31]
the response is
```
{
    "code": 2003,
    "msg": "已报名该考试",
    "data": null
}
```
while student is not enrolled.

**Comment by QYR22** [comment]
[缺陷问题报告单_exam考试-enroll](https://s1g6wd6uvji.feishu.cn/sheets/RkD7sw3EphsMMmtBtwfctHkpnlh?sheet=0ncO4G)
