### ISSUE TITLE
Missing feature: The teacher's end lacks the ability to view all students in a single exam and their respective answer sheets.

### ISSUE THREAD

**Issue by QYR22** [VirtualPetHospital/backend#56]
Missing feature: The teacher's end lacks the ability to view all students in a single exam and their respective answer sheets. The feature design lacks thorough consideration.

**Comment by QYR22** [comment]
[缺陷问题报告单_answer-sheet答题卡-新增功能-老师端查看单场考试所有学生答题卡](https://r0o7ljwxopa.feishu.cn/sheets/WXTQsvBNrhr2KEt1eoDcv2Vbnjb?sheet=fIoZe8)

**Comment by astarforbae** [comment]
[cb9b970](https://github.com/VirtualPetHospital/backend/commit/cb9b970a0be4a92dde06ace67421788395774398) fixed
